use_frameworks!

target 'RenetikLayout_Example' do
  pod 'RenetikLayout', :path => '../'

  target 'RenetikLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
